server:
  port: 80
spring:
  datasource:
    url: jdbc:oracle:thin:@172.16.20.67:1521:xe
    username: epay
    password: 12345
    driver-class-name: oracle.jdbc.driver.OracleDriver 
  jpa:
    database: oracle
    show-sql: true
 
    