server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://47.100.164.143:3306/test
    username: root
    password: 905520
    driver-class-name: com.mysql.jdbc.Driver 
  jpa:
    database: mysql
    show-sql: true
 
    