server:
  port: 80
spring:
  datasource:
    #url: jdbc:oracle:thin:@//192.168.8.110:1521/IPCC
    url: jdbc:oracle:thin:@127.0.0.1:1521:xe
    username: epay
    password: 12345
    driver-class-name: oracle.jdbc.driver.OracleDriver 
  jpa:
    database: oracle
    show-sql: true
 
    